### ISSUE TITLE
Add a resnet example.

### ISSUE THREAD

**Issue by htomtom** [ameritusweb/ParallelReverseAutoDiff#7]
This is a convenient & extensible repository. Does this library support resnet structure? If so, can you add an example of resnet, or point out how to support the operations.

**Comment by ameritusweb** [comment]
Yeah, I can expand on the CNN example, add residual connections, and use the CIFAR-10 dataset as training data for an image classification task.

**Comment by htomtom** [comment]
Very well. If the residual module can be added into the CNN example and be able to train the CIFAR-10 dataset, it will be a good illustration of the usability and scalability of the project. Am looking forward to test it.
